# XBox 360 Controller
# Deadman (enable) button: RB
# D<>X button (located on the back panel) must be set to D

# XBox360 USB Controller mapping with joy_linux node
# Buttons
#   0=A / 1=B / 2=X / 3=Y / 4=LB / 5=RB / 6=Back / 7=Start / 8=XBox / 9=LeftJoyClick / 10=RightJoyClick
# Axes
#   0=LeftJoyX / 1=LeftJoyY / 2=LeftTrigger / 3=RightJoyX / 4=RightJoyY / 5=RightTrigger / 6=PadX / 7=PadY
/**:
  ros__parameters:
    piloting:
      type: topic
      interface_type: "geometry_msgs/msg/Twist"
      topic_name: cmd_vel
      deadman_buttons: [5]  # RT
      axis_mappings:
        linear-x:
          axis: 1
          scale: 3.0
          offset: 0
        linear-y:
          axis: 0
          scale: 2.0
          offset: 0
        angular-z:
          axis: 3
          scale: 4.0
          offset: 0
    yellow:
      type: topic
      interface_type: "robomaster_msgs/msg/LEDEffect"
      topic_name: leds/effect
      deadman_buttons: [5,3]  # RB + Y
      message_value:
        color-r:
          value: 1.0
        color-g:
          value: 1.0
    blue:
      type: topic
      interface_type: "robomaster_msgs/msg/LEDEffect"
      topic_name: leds/effect
      deadman_buttons: [5,2]  # RB + X
      message_value:
        color-b:
          value: 1.0
    green:
      type: topic
      interface_type: "robomaster_msgs/msg/LEDEffect"
      topic_name: leds/effect
      deadman_buttons: [5,0]  # RB + A
      message_value:
        color-g:
          value: 1.0
    red:
      type: topic
      interface_type: "robomaster_msgs/msg/LEDEffect"
      topic_name: leds/effect
      deadman_buttons: [5,1]  # RB + B
      message_value:
        color-r:
          value: 1.0
    off:
      type: topic
      interface_type: "robomaster_msgs/msg/LEDEffect"
      topic_name: leds/effect
      deadman_buttons: [5,8]  # RB + back
      message_value:
        effect:
          value: 0
    close_gripper:
      type: action
      interface_type: robomaster_msgs/action/GripperControl
      action_name: gripper
      action_goal:
        target_state: 2
      buttons: [4, 2] # LB + X
    open_gripper:
      type: action
      interface_type: robomaster_msgs/action/GripperControl
      action_name: gripper
      action_goal:
        target_state: 1
      buttons: [4, 1] # LB + B
    comarm:
      type: topic
      interface_type: "geometry_msgs/msg/Vector3"
      topic_name: cmd_arm
      deadman_buttons: [4]  # RT
      axis_mappings:
        x:
          axis: 4
          scale: 0.2
          offset: 0
        z:
          axis: 3
          scale: 0.2
          offset: 0
    engage:
      type: service
      interface_type: std_srvs/srv/SetBool
      service_name: engage_wheels
      service_request:
        data: true
      buttons: [7] # Start
    disengage:
      type: service
      interface_type: std_srvs/srv/SetBool
      service_name: engage_wheels
      service_request:
        data: false
      buttons: [6] # Back

